function createfigure_bar_non_it(non_it,fid)
%CREATEFIGURE1(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 10-Mar-2010 14:36:43

% Create figure
figure1 = figure('Name','Nonlinear Iterations Bar Plot','Color',[1 1 1]);

max_non_it=max(non_it);
mean_non_it=mean(non_it);
min_non_it=min(non_it);

fprintf(fid,'\n');
fprintf(fid,'Maximum Number Nonlinear Iterations = %i\n',max_non_it);
fprintf(fid,'Mean Number Nonlinear Iterations    = %f\n',mean_non_it);
fprintf(fid,'Minimum Number Nonlinear Iterations = %i\n',min_non_it);

small=zeros(max_non_it,1);

for i=1:max_non_it
   small(i)=(100.0*length(find(non_it==i))/length(non_it));
   labels{i}=num2str((i));
end

%labels{1}=strcat(label{1},'_to_',label{2});
%labels{1}=regexprep(labels{1},'_',' ');
%labels{2}=strcat(label{2},'_to_',label{3});
%labels{2}=regexprep(labels{2},'_',' ');
%labels{3}=strcat(label{3},'_to_',label{4});
%labels{3}=regexprep(labels{3},'_',' ');
%labels{4}=strcat(label{4},'_to_',label{5});
%labels{4}=regexprep(labels{4},'_',' ');
%labels{5}=strcat(label{5});
%labels{5}=regexprep(labels{5},'_',' ');

% Create axes


axes1 = axes('Parent',figure1,'XTick',[1 2 3 4 5 6 7 8 9 10], 'XTickLabel', ...
    {labels{:}} );
box(axes1,'on');
hold(axes1,'all');

% Create bar
bar(small);
set(gca,'ylim',[0 20])
% Create ylabel
ylabel('Percentage of Occurrences','FontWeight','bold',...
    'FontSize',16);

xlabel('Number of Required Nonlinear Iterations','FontWeight','bold',...
    'FontSize',16);

% Create title
title('Nonlinear Iterations Bar Plot','FontWeight','bold','FontSize',20);

