function createfigure_bar_dt(dt,fid)
%CREATEFIGURE1(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 10-Mar-2010 14:36:43

% Create figure
figure1 = figure('Name','Time Step Bar Plot','Color',[1 1 1]);

max_dt=max(dt);
mean_dt=mean(dt);
min_dt=min(dt);

fprintf(fid,'\n');
fprintf(fid,'Maximum Time Step                   = %i\n',max_dt);
fprintf(fid,'Mean Time Step                      = %f\n',mean_dt);
fprintf(fid,'Minimum Time Step                   = %i\n',min_dt);
fprintf(fid,'Total Number of Time Steps          = %i\n',length(dt));

%small1(1)=int32(length(find(dt<(max_dt/8))));

%small1(2)=int32(length(find(dt<(max_dt/4))));

%small1(3)=int32(length(find(dt<(max_dt/2))));

%small1(4)=int32(length(find(dt<(max_dt))));

%small1(5)=int32(length(find(dt==(max_dt))));

small1(1)=(length(find(dt<(max_dt/8))));

small1(2)=(length(find(dt<(max_dt/4))));

small1(3)=(length(find(dt<(max_dt/2))));

small1(4)=(length(find(dt<(max_dt))));

small1(5)=(length(find(dt==(max_dt))));

small(1)=100.0*small1(1)/length(dt);
small(2)=100.0*(small1(2)-small1(1))/length(dt);
small(3)=100.0*(small1(3)-small1(2))/length(dt);
small(4)=100.0*(small1(4)-small1(3))/length(dt);
small(5)=100.0*small1(5)/length(dt);

label{1}='0'; 
label{2}=num2str((max_dt/8)); 
label{3}=num2str((max_dt/4)); 
label{4}=num2str((max_dt/2)); 
label{5}=num2str((max_dt)); 

labels{1}=strcat(label{1},'_to_',label{2});
labels{1}=regexprep(labels{1},'_',' ');
labels{2}=strcat(label{2},'_to_',label{3});
labels{2}=regexprep(labels{2},'_',' ');
labels{3}=strcat(label{3},'_to_',label{4});
labels{3}=regexprep(labels{3},'_',' ');
labels{4}=strcat(label{4},'_to_',label{5});
labels{4}=regexprep(labels{4},'_',' ');
labels{5}=strcat(label{5});
labels{5}=regexprep(labels{5},'_',' ');

% Create axes

axes1 = axes('Parent',figure1,'XTick',[1 2 3 4 5], 'XTickLabel', ...
    {labels{1} labels{2} labels{3} labels{4} labels{5}});
box(axes1,'on');
hold(axes1,'all');
%small
% Create bar
bar(small);
set(gca,'ylim',[0 50])
% Create ylabel
ylabel('Percentage of Occurrences','FontWeight','bold',...
    'FontSize',16);

xlabel('Time Step Sizes (Seconds)','FontWeight','bold',...
    'FontSize',16);

% Create title
title('Time Step Bar Plot','FontWeight','bold','FontSize',20);

