function createfigure2(X1, Y1, X2, Y2,field_data_file,y_name)
%CREATEFIGURE3(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 20-Feb-2010 19:50:45

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes

axes1 = axes('Parent',figure1,'FontSize',12,'FontName','Times New Roman');
box(axes1,'on');
hold(axes1,'all');

min_x1=min(X1);
min_x2=min(X2);
max_x1=max(X1);
max_x2=max(X2);
min_y1=min(Y1);
min_y2=min(Y2);
max_y1=max(Y1);
max_y2=max(Y2);
min_x=max(min_x1,min_x2);
max_x=min(max_x1,max_x2);
min_y=min(min_y1,min_y2);
max_y=max(max_y1,max_y2);
axis([min_x max_x min_y max_y])
datetick('x',2,'keepticks')

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',0.5,'DisplayName','Model Data');

% Create plot
plot(X2,Y2,'Parent',axes1,'LineWidth',0.5,'DisplayName','Measured Field Data');

% Create xlabel
xlabel({'Time'},'FontSize',16,'FontName','Times New Roman');

% Create ylabel
ylabel({y_name},'FontSize',16,...
    'FontName','Times New Roman');

len=size(field_data_file);
name=field_data_file(1:(len(2)-4));

plot_title=strcat( ...
    'Water Surface Elevations Comparison Plots for', '_',name);
plot_title=regexprep(plot_title,'_',' ');

% Create title
title(plot_title,'FontSize',16,...
    'FontName','Times New Roman');



% Create legend
legend1 = legend(axes1,'show');


