function createfigure2_dis(X1, Y1, X2, Y2,field_data_file,y_name,plot_title)
%CREATEFIGURE3(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 20-Feb-2010 19:50:45

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes

axes1 = axes('Parent',figure1,'FontSize',12,'FontName','Times New Roman');
hold(axes1,'all');
box(axes1,'on');
min_x1=min(X1);
min_x2=min(X2);
max_x1=max(X1);
max_x2=max(X2);
min_x=max(min_x1,min_x2);
max_x=min(max_x1,max_x2);
start=find(X1>=min_x-0.5,1,'first');
stop=find(X1<=max_x+0.5,1,'last');
min_y1=min(Y1(start:stop));
max_y1=max(Y1(start:stop));
start=find(X2>=min_x-0.5,1,'first');
stop=find(X2<=max_x+0.5,1,'last');
min_y2=min(Y2(start:stop));
max_y2=max(Y2(start:stop));

min_y=min(min_y1,min_y2);
max_y=max(max_y1,max_y2);
range=abs(min_y)+abs(max_y)/2;
axis([min_x-0.5 max_x+0.5 min_y max_y])
datetick('x',2,'keepticks')


axis([min_x-0.5 max_x+0.5 min_y-0.2*range max_y+0.2*range])

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',1.0,'DisplayName','Model Data');

% Create plot
plot(X2,Y2,'Parent',axes1,'MarkerFaceColor',[1 0 0],...
    'MarkerEdgeColor',[1 0 0],...
    'MarkerSize',10,...
    'Marker','pentagram',...
    'LineStyle','none',...
    'Color',[1 0 0],...
    'DisplayName','Measured Field Data');
%plot(X2,Y2,'ro','MarkerSize',10);
% Create xlabel
xlabel({'Time'},'FontSize',16,'FontName','Times New Roman');

% Create ylabel
ylabel({y_name},'FontSize',16,...
    'FontName','Times New Roman');

%location=find(field_data_file=='T');
%tran=str2double(field_data_file(location+1));

%if(tran==1)
%    transect='Transect 1';
%elseif(tran==2)
%    transect='Transect 2';
%elseif(tran==3)
%    transect='Transect 3';
%elseif(tran==4)
%    transect='Transect 4';
%elseif(tran==5)
%    transect='Transect 5';
%elseif(tran==6)
%    transect='Transect 6';
%elseif(tran==7)
%    transect='Transect 7';
%elseif(tran==8)
%    transect='Transect 8';
%elseif(tran==9)
%    transect='Transect 9';
%end

plot_title=strcat(plot_title, '_', field_data_file);
plot_title=regexprep(plot_title,'_',' ');

% Create title
title(plot_title,'FontSize',16,...
    'FontName','Times New Roman');



% Create legend
legend1 = legend(axes1,'show','Location','Best');


