function figs(X1, Y1,x_name,y_name,plot_title)
%CREATEFIGURE3(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 20-Feb-2010 19:50:45

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes

axes1 = axes('Parent',figure1,'FontSize',12,'FontName','Times New Roman');
box(axes1,'on');
hold(axes1,'all');

min_x=min(X1);
max_x=max(X1);
min_y=min(Y1);
max_y=max(Y1);
%axis([min_x max_x min_y max_y])

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',0.5,'DisplayName','Model Data');

% Create xlabel
xlabel({x_name},'FontSize',16,'FontName','Times New Roman');

% Create ylabel
ylabel({y_name},'FontSize',16,...
    'FontName','Times New Roman');

% Create title
title(plot_title,'FontSize',16,...
    'FontName','Times New Roman');




