function plots(X1,Raw_X,Filtered_X,Raw_Y,Filtered_Y,name)
%CREATEFIGURE1(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 25-Apr-2010 10:33:34

temp1=datenum('01/01/2008 00:00:00');

temp2=datenum('01/01/2009 00:00:00');


% Create figure
figure1 = figure('Color',[1 1 1]);
datetick('x',2,'keepticks')
% Create axes
%axes1 = axes('Parent',figure1,'OuterPosition',[0 0.5 1 0.5],'FontSize',14);
%box('on');
hold on;
% Create multiple lines using matrix input to plot
a = subplot(2,1,1);
plot(X1,Raw_X,'-r','LineWidth',0.5,'DisplayName','Raw X Component');
plot(X1,Filtered_X,'-b','LineWidth',0.5,'DisplayName','Filtered X Component');

% Create ylabel
ylabel('Wind Speed (m/s)','FontWeight','bold','FontSize',16);

% Create title
title('Wind Filtering','FontWeight','bold','FontSize',20);

% Create legend
legend('show');

datetick('x',2,'keepticks')
%axis([min(X1) max(X1) min(min(Raw_X),min(Filtered_X)) max(max(Raw_X),max(Filtered_X))])
% Create axes
%axes2 = axes('Parent',figure1,...
%    'Position',[0.13 0.0716414523449319 0.775 0.4075],...
%    'FontSize',14);
%box('on');
hold on;
% Create multiple lines using matrix input to plot
b = subplot(2,1,2);
plot(X1,Raw_Y,'-r','LineWidth',0.5,'DisplayName','Raw Y Component');
plot(X1,Filtered_Y','-b','LineWidth',0.5,'DisplayName','Filtered Y Component');

legend('show');
% Create xlabel
xlabel('Time','FontWeight','bold','FontSize',16);
%feather(axes2,Raw_X,Raw_Y);
% Create ylabel
ylabel('Wind Speed (m/s)','FontWeight','bold','FontSize',16);
% Create legend
linkaxes([a b], 'x');
axis([temp1 temp2 min(min(Raw_Y),min(Filtered_Y)) max(max(Raw_Y),max(Filtered_Y))])
datetick('x',2,'keepticks')
%axis([min(X1) max(X1) min(min(Raw_Y),min(Filtered_Y)) max(max(Raw_Y),max(Filtered_Y))])





%set(a,'XTick',temp1:60:temp2)
%set(b,'XTick',temp1:60:temp2)

datetick('x',2,'keepticks')

%set(gcf,'XTick',temp1:60:temp2)

%datetick('x',2,'keepticks')

%set(gcf,'renderer','zbuffer');
%opengl neverselect
%set(gcf,'Backingstore','off','doublebuffer','on'); 

saveas(gcf,[name '_2008'],'fig');
saveas(gcf,[name '_2008'],'png');

%temp1=datenum('01/01/2009 00:00:00');

%temp2=datenum('01/01/2010 00:00:00');

%set(axes1,'XTick',temp1:60:temp2)

%datetick('x',2,'keepticks')

%set(axes2,'XTick',temp1:60:temp2)

%datetick('x',2,'keepticks')

%set(gcf,'renderer','zbuffer');
%opengl neverselect
%set(gcf,'Backingstore','off','doublebuffer','on'); 

%saveas(gcf,[name '_2009'],'fig');
%saveas(gcf,[name '_2009'],'png');

%temp1=datenum('01/01/2010 00:00:00');

%temp2=datenum('01/01/2011 00:00:00');

%set(axes1,'XTick',temp1:60:temp2)

%datetick('x',2,'keepticks')

%set(axes2,'XTick',temp1:60:temp2)

%datetick('x',2,'keepticks')

%set(gcf,'renderer','zbuffer');
%opengl neverselect
%set(gcf,'Backingstore','off','doublebuffer','on'); 

%saveas(gcf,[name '_2010'],'fig');
%saveas(gcf,[name '_2010'],'png');

close(gcf);






