function plot_harmonic_comparison(model_TIDECON,field_TIDECON,field_data_file,harm_name)


%  loc_M2=11;
%  loc_S2=12;
%  loc_K1=6;
%  loc_N2=10;
%  loc_O1=4;
%  loc_M4=19;
avg=zeros(length(model_TIDECON),1);
for i=1:length(model_TIDECON)

    avg(i)=(model_TIDECON(i)+field_TIDECON(i))/2.0;
    
end

for i=1:length(model_TIDECON)
   
    max1=max(avg);
    
    loc(i)=find(avg==max1,1,'first');
    avg(loc(i))=0.0;
    
end

model_con=model_TIDECON(loc(1:10));
field_con=field_TIDECON(loc(1:10));
con_name=harm_name(loc(1:10),:);

%model_TIDECON
%field_TIDECON
%harm_name

 % bar(field_TIDECON(loc_M2,1));

%% Creates the figure

figure1 = figure('Color',[1 1 1]);

%% determine the minimum and maximum values to use for the plot bounds

bot=min(min(field_TIDECON(:,1)),min(model_TIDECON(:,1)));
top=max(max(field_TIDECON(:,1)),max(model_TIDECON(:,1)));
bot=0;
top=top+0.5;



%% create and specify the axis properties

axes1 = axes('Parent',figure1,'FontSize',12,'FontName', ...
    'Times New Roman');
set(axes1,'XLim',[bot top]);
set(axes1,'YLim',[bot top]);
box(axes1,'on');
hold(axes1,'all');


%% Create the scatter plot

plot(field_con(1),model_con(1), ...
    'rs', 'MarkerEdgeColor','r',...
                'MarkerFaceColor','r',...
                'MarkerSize',7, 'DisplayName',harm_name(1,:));
            
plot(field_con(2),model_con(2), ...
    'gp', 'MarkerEdgeColor','g',...
                'MarkerFaceColor','g',...
                'MarkerSize',8, 'DisplayName',harm_name(2,:));
            
plot(field_con(3),model_con(3), ...
    'mx', 'MarkerEdgeColor','m',...
                'MarkerFaceColor','m',...
                'MarkerSize',10, 'DisplayName',harm_name(3,:));
            
plot(field_con(4),model_con(4), ...
    'cd', 'MarkerEdgeColor','c',...
                'MarkerFaceColor','c',...
                'MarkerSize',8, 'DisplayName',harm_name(4,:));
            
plot(field_con(5),model_con(5), ...
    'kh', 'MarkerEdgeColor','k',...
                'MarkerFaceColor','k',...
                'MarkerSize',8, 'DisplayName',harm_name(5,:));
            
plot(field_con(6),model_con(6), ...
    'bo', 'MarkerEdgeColor','b',...
                'MarkerFaceColor','b',...
                'MarkerSize',7, 'DisplayName',harm_name(6,:));
            
plot(field_con(7),model_con(7), ...
    'r^', 'MarkerEdgeColor','r',...
                'MarkerFaceColor','r',...
                'MarkerSize',8, 'DisplayName',harm_name(7,:));
            
plot(field_con(8),model_con(8), ...
    'gv', 'MarkerEdgeColor','g',...
                'MarkerFaceColor','g',...
                'MarkerSize',8, 'DisplayName',harm_name(8,:));
            
plot(field_con(9),model_con(9), ...
    'm>', 'MarkerEdgeColor','m',...
                'MarkerFaceColor','m',...
                'MarkerSize',8, 'DisplayName',harm_name(9,:));
            
plot(field_con(10),model_con(10), ...
    'c<', 'MarkerEdgeColor','c',...
                'MarkerFaceColor','c',...
                'MarkerSize',8, 'DisplayName',harm_name(10,:));            
            
            


%% create the string to use for the x-axis label

temp=strcat('Field Data Amplitude, meters');
%temp=regexprep(temp,'_',' ');

%% Set the x-axis label and font type/size

xlabel({temp},'FontSize',16,'FontName','Times New Roman');

%% create the string to use for the y-axis label

temp=strcat('Model Data Amplitude, meters');
%temp=regexprep(temp,'_',' ');

%% Set the y-axis label and font type/size

ylabel({temp},'FontSize',16,'FontName','Times New Roman');

%% create the string to use for the plot title

plot_title=strcat(['Harmonic Constituent Comparisons for_' field_data_file]);
plot_title=regexprep(plot_title,'_',' ');

%% Set the plot title and font type/size

title(plot_title,'FontSize',16,...
    'FontName','Times New Roman');

legend('show','location','EastOutside')

%% Create a line to represent the ideal match of field verus model

line([bot-abs(top) top+abs(top)], [bot-abs(top) top+abs(top)], ...
    'LineWidth',2.0,'Color',[0 0 0]);

%% Create the scatter plot

plot(field_con(1),model_con(1), ...
    'rs', 'MarkerEdgeColor','r',...
                'MarkerFaceColor','r',...
                'MarkerSize',7, 'DisplayName',harm_name(1));
            
plot(field_con(2),model_con(2), ...
    'gp', 'MarkerEdgeColor','g',...
                'MarkerFaceColor','g',...
                'MarkerSize',8, 'DisplayName',harm_name(2));
            
plot(field_con(3),model_con(3), ...
    'mx', 'MarkerEdgeColor','m',...
                'MarkerFaceColor','m',...
                'MarkerSize',8, 'DisplayName',harm_name(3));
            
plot(field_con(4),model_con(4), ...
    'cd', 'MarkerEdgeColor','c',...
                'MarkerFaceColor','c',...
                'MarkerSize',8, 'DisplayName',harm_name(4));
            
plot(field_con(5),model_con(5), ...
    'kh', 'MarkerEdgeColor','k',...
                'MarkerFaceColor','k',...
                'MarkerSize',8, 'DisplayName',harm_name(5));
            
plot(field_con(6),model_con(6), ...
    'bo', 'MarkerEdgeColor','b',...
                'MarkerFaceColor','b',...
                'MarkerSize',7, 'DisplayName',harm_name(6));
            
plot(field_con(7),model_con(7), ...
    'r^', 'MarkerEdgeColor','r',...
                'MarkerFaceColor','r',...
                'MarkerSize',8, 'DisplayName',harm_name(7));
            
plot(field_con(8),model_con(8), ...
    'gv', 'MarkerEdgeColor','g',...
                'MarkerFaceColor','g',...
                'MarkerSize',8, 'DisplayName',harm_name(8));
            
plot(field_con(9),model_con(9), ...
    'm>', 'MarkerEdgeColor','m',...
                'MarkerFaceColor','m',...
                'MarkerSize',8, 'DisplayName',harm_name(9));
            
plot(field_con(10),model_con(10), ...
    'c<', 'MarkerEdgeColor','c',...
                'MarkerFaceColor','c',...
                'MarkerSize',8, 'DisplayName',harm_name(10));  
 
  
