function importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 20-Feb-2010 21:33:19

DELIMITER = '\t';
HEADERLINES = 20;

% Import the file
rawData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% return a simple array.  If so, generate a structure so that the output
% matches that from the Import Wizard.
[~,name] = fileparts(fileToRead1);
newData1.(genvarname(name)) = rawData1;

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

count=1;

while(~feof(fid))
   year(count)=fscanf(fid,'%4i',1)
   month(count)=fscanf(fid,'%2i',1)
   day(count)=fscanf(fid,'%2i',1)
   hour(count)=fscanf(fid,'%2i',1)
   minute(count)=fscanf(fid,'%2i',1)
   second(count)=fscanf(fid,'%2i',1);
   hold1=fscanf(fid,'%s',1);
   value(count)=fscanf(fid,'%f',1)
   hold2=fscanf(fid,'%i',1);
   hold3=fscanf(fid,'%s',1);
   hold4=fscanf(fid,'%s',1);
   count=count+1
end

fclose(fid);
