tic

clear

% ADH root filename

basename='Bush_Canal';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%% WATER SURFACE ELEVATION INPUT INFORMATION %%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Title to use for plots to be followed by the data filename

plot_title{1}='Water Surface Elevation Comparison Plots for ';

% Y-axis Label

y_label{1}='Water Surface Elevation, ft, NAVD88(2004.65)';

% output filename for the analysis 

analysis_output_file{1}='gage_analysis_file_wse.txt'; 

%%%      data files containing the raw field data             %%%

wse_field_data_file   = {                               ...
    'data\Caillou_Bay_USGS.txt'                       ; ...
    'data\Bayou_Terrebonne_CHL.prn'                   ; ...
    'data\Placid_Canal_CHL.prn'                       ; ...
    'data\Bayou_Grand_Caillou_CHL.prn'                ; ...
    'data\GIWW_Near_Larose_CHL.txt'                   ; ...
    'data\Bayou_Petit_Caillou_CHL.prn'                ; ...
    'data\Caillou_Lake_USGS.txt'                      ; ...
    'data\Bayou_Grand_Caillou_USGS.txt'               ; ...
    'data\GIWW_at_Houma_USGS.txt'                     ; ...
    'data\GIWW_at_Larose_USGS.txt'                    ; ...
    'data\Company_Canal_near_Lockport_USGS.txt'       ; ...
    'data\Bayou_Petit_Caillou_USGS.txt'               ; ...
    'data\Bayou_Terrebonne_USGS.txt'                  ; ...
    'data\Houma_Navigational_Canal_USGS.txt'          ; ...
    'data\Falgout_Canal_CHL.prn'                      ; ...
    'data\GIWW_West_of_Houma_CHL.txt'                 ; ...
    'data\Grand_Bayou_CHL.prn'                        ; ...
    'data\Humble_Canal_CHL.prn'                       ; ...
    'data\Bayou_Dularge_CHL.prn'                      ; ...
    'data\Lapeyrouse_Canal_CHL.prn'}               ;

%%%    first number is the x coordinate for each gage         %%%
%%%   second number is the y coordinate for each gage         %%%
%%%    third number is the read format for the data file      %%%

wse_field_data_format = [                               ...
    3428374.0371398,     210608.63755536, 1;            ...
    3518214.0	   ,     324448.0       , 6;            ...
    3504031.0	   ,     306598.0       , 7;            ...
    3472126.951572 ,     305091.83650439, 6;            ...
    3586186.0805712,	 397357.97240739, 6;            ...
    3499190.0715083,	 290522.3829524 , 7;            ...
    3412266.4665589,     272769.24998097, 1;            ...
    3477814.0      ,     321658.0       , 1;            ...
    3478903.2750316,     399942.04495628, 1;            ...
    3582625.0      ,     391116.0       , 1;            ...
    3527243.1048071,     410881.25127938, 1;            ...
    3508781.0      ,     323294.0       , 1;            ...
    3518135.0      ,     323828.0       , 1;            ...
    3473044.3627297,     322433.21654367, 1;            ...
    3454360.0	   ,     333230.0       , 6;            ...
    3467998.3261517,	 386752.1280483 , 6;            ...
    3577053.0	   ,     378029.0       , 6;            ... 
    3526095.8471264,	 341317.54372905, 6;            ...
    3454819.0	   ,     330584.0       , 7;            ...
    3500026.9855289,	 294797.05638406, 7             ...  
    ];     


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%% DISCHARGE INPUT INFORMATION %%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Title to use for plots to be followed by the data filename

plot_title{2}='Discharge Comparison Plots for ';

% Y-axis Label

y_label{2}='Discharges, cfs';

% output filename for the analysis 

analysis_output_file{2}='gage_analysis_file_dis.txt'; 

% If reading the ADH outputted flux file, need to set initial time

t0='07/01/2009 00:00:00';

%%%         data files for the raw field discharge data                 %%%

dis_field_data_file   = {                                      ...
    'discharge\Bayou_Grand_Caillou_at_Dulac_USGS.txt'        ; ...
    'discharge\GIWW_West_of_Bayou_Lafourche_USGS.txt'        ; ...
    'discharge\GIWW_at_Houma_USGS.txt'                       ; ...
    'discharge\Houma_Navigational_Canal_at_Dulac_USGS.txt'   ; ...
    'discharge\Bayou_Dularge_CHL.prn'                        ; ...
    'discharge\Bayou_Grand_Caillou_CHL.prn'                  ; ...
    'discharge\Bayou_Petit_Caillou_CHL.prn'                  ; ...
    'discharge\Bayou_Terrebonne_CHL.prn'                     ; ...
    'discharge\Falgout_Canal_CHL.prn'                        ; ...
    'discharge\GIWW_West_of_Houma_CHL.txt'                   ; ...
    'discharge\Grand_Bayou_CHL.prn'                          ; ...
    'discharge\Humble_Canal_CHL.prn'                         ; ...
    'discharge\Lapeyrouse_Canal_CHL.prn'                     ; ...
    'discharge\Placid_Canal_CHL.prn'                         ; ...
    };

%%%               first number is the flux string number                %%%
%%% second number is to flip the sign of the model discharged if needed %%% 
%%%                  third number is the read format                    %%%

dis_field_data_format = [                                      ...
     25 -1  1;                                                  ...
     21  1  1;                                                  ...
     26  1  1;                                                  ...
     24 -1  1;                                                  ...
     19 -1  7;                                                  ...
     23 -1  6;                                                  ...
     18 -1  7;                                                  ...
     15 -1  6;                                                  ...
     27  1  6;                                                  ...
     20  1  6;                                                  ...
     13  1  6;                                                  ...
     14  1  6;                                                  ...
     17  1  7;                                                  ...
     16  1  7;                                                  ...
    ];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%CHECKS FOR INCONSISTANT INPUT VARIABLES AND STARTS ANALYSIS IF  %%%%%
%%%%%%APPROPRIATE.  PERFORMS THE WSE ANALYSIS FIRST AND THEN PERFORMS %%%%%
%%%%%%                 THE DISCHARGE ANALYSIS                         %%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if(isequal(length(wse_field_data_format),length(wse_field_data_file)) && ...
        length(wse_field_data_format) >= 1)
    wse_analysis(wse_field_data_format,wse_field_data_file, ...
        plot_title{1},y_label{1},analysis_output_file{1},basename);
else
    fprintf(1,'ERROR!!!!!!\n')
    fprintf(1,'NUMBER OF WSE INPUT ENTRY VALUES ARE NOT EQUAL\n')
    fprintf(1,'NUMBER OF INPUT FILES    = %i\n',length(field_data_file))
    fprintf(1,'NUMBER OF GAGE LOCATIONS = %i\n',length(gage_locations))
end

if(isequal(length(dis_field_data_format),length(dis_field_data_file)) && ...
        length(dis_field_data_format) >= 1)
    discharge_analysis(dis_field_data_file,dis_field_data_format, ...
    plot_title{2},y_label{2},analysis_output_file{2},basename, t0);
else
    fprintf(1,'ERROR!!!!!!\n')
    fprintf(1,'NUMBER OF DISCHARGE INPUT ENTRY VALUES ARE NOT EQUAL\n')
    fprintf(1,'NUMBER OF INPUT FILES         = %i\n',length(dis_field_data_file))
    fprintf(1,'NUMBER OF FILE FORMATS        = %i\n',length(dis_field_data_format))
end

toc

