      PROGRAM NODE2MIX
      PARAMETER (MNN = 100, MAXT = 2000)
      CHARACTER FILENAME*80
      DIMENSION NODE(MNN),TIME(MAXT),WSE(MNN,MAXT),VEL(MNN,MAXT)
      
      PRINT *,'ENTER THE NODE2GET SUMMARY FILE NAME TO REWORK'
      READ(*,'(A)') FILENAME
      OPEN(2,FILE=FILENAME,FORM='FORMATTED',STATUS='OLD')
      
      PRINT *,'ENTER THE OUTPUT WSE FILE NAME THAT IS REWORKED'
      READ(*,'(A)') FILENAME
      OPEN(3,FILE=FILENAME,FORM='FORMATTED',STATUS='UNKNOWN')
     
      PRINT *,'ENTER THE OUTPUT VEL FILE NAME THAT IS REWORKED'
      READ(*,'(A)') FILENAME
      OPEN(4,FILE=FILENAME,FORM='FORMATTED',STATUS='UNKNOWN')
     
      PRINT *,'TELL ME THE NUMBER OF TIMESTEPS  FOR EACH NODE'
      PRINT *,' YOU BETTER GET IT RIGHT OR I WILL CRASH AND BURN'
      READ *,NSTEP
      
      PRINT *,' WHAT IS THE DOMINANT FLOOD QUADRANT??'
      PRINT *,'  THAT IS THE DIRECTION TOWARD WHICH '
      PRINT *,'  THE FLOOD CURRENT FLOWS'
      PRINT *,'     NE = 1 '
      PRINT *,'     NW = 2 '
      PRINT *,'     SW = 3 '
      PRINT *,'     SE = 4 '
      PRINT *,'  ENTER 1, 2, 3, OR 4:'
      READ *, IQUAD
      FX = 1.0
      FY = 1.0
      IF(IQUAD .EQ. 2  .OR. IQUAD .EQ. 3) FX = -1.0
      IF(IQUAD .GT. 2 ) FY = -1.0
      
      
      I=0
  10  LML = 1
      I = I + 1
      READ(2,2000,END=30) NODE(I)
 2000 FORMAT(21X,I6)
      DO 20 J=1,NSTEP
      READ(2,*) TIME(J),X,Y,WSE(I,J)
      VMAG = SQRT(X*X+Y*Y)
      S = FX * SIGN(1.0,X)
      IF(ABS(Y) .GT. ABS(X) ) S = FY * SIGN(1.0,Y)
      VEL(I,J) = S * VMAG
  20  CONTINUE
      GOTO 10
  30  LML =1
      I=I-1
      WRITE(3,3000)   (NODE(K),K=1,I)
 3000 FORMAT('  TIME    ', 25I7)
 
      DO 100 J=1,NSTEP
      WRITE(3,3001) TIME(J),(WSE(K,J),K=1,I)
      WRITE(4,3002) TIME(J),(VEL(K,J),K=1,I)
 3001 FORMAT(F8.3,30F7.3)
 3002 FORMAT(F8.3,30F7.3)
  100 CONTINUE
  
      STOP
      END
      